language: python
python:
 - "2.7"
 - "3.3"
# command to install dependencies
before_install:
  - sudo apt-get install libglpk-dev libgmp-dev
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install glpk -f http://clostridium.ucsd.edu/wheelhouse; fi
  - pip install python-libsbml-experimental cython numpy scipy -f http://clostridium.ucsd.edu/wheelhouse
install:
  - python setup.py develop
# # command to run tests
script: python setup.py test
